-- Esquema inicial definitivo para PostgreSQL.
-- Ejecutar solamente en una base donde estas seis tablas todavía no existan.
BEGIN;

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL,
    rol VARCHAR(30) NOT NULL DEFAULT 'estudiante',
    contrasena VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100),
    email_verified_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('profesor', 'estudiante'))
);

CREATE TABLE actividad (
    id_actividad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_actividad VARCHAR(150) NOT NULL,
    descripcion_actividad VARCHAR(200),
    instrucciones VARCHAR(200),
    fecha_creacion_actividad TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE seccion (
    id_seccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    nombre_seccion VARCHAR(200) NOT NULL,
    descripcion_seccion VARCHAR(300),
    CONSTRAINT fk_seccion_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE RESTRICT
);

CREATE TABLE seccion_estudiante (
    id_seccion INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_inscripcion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_seccion_estudiante PRIMARY KEY (id_seccion, id_usuario),
    CONSTRAINT fk_seccion_estudiante_seccion FOREIGN KEY (id_seccion)
        REFERENCES seccion (id_seccion) ON DELETE CASCADE,
    CONSTRAINT fk_seccion_estudiante_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE
);

CREATE TABLE seccion_actividad (
    id_seccion INTEGER NOT NULL,
    id_actividad INTEGER NOT NULL,
    CONSTRAINT pk_seccion_actividad PRIMARY KEY (id_seccion, id_actividad),
    CONSTRAINT fk_seccion_actividad_seccion FOREIGN KEY (id_seccion)
        REFERENCES seccion (id_seccion) ON DELETE RESTRICT,
    CONSTRAINT fk_seccion_actividad_actividad FOREIGN KEY (id_actividad)
        REFERENCES actividad (id_actividad) ON DELETE RESTRICT
);

CREATE TABLE codigo (
    id_codigo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actividad INTEGER,
    id_usuario INTEGER NOT NULL,
    nombre_codigo VARCHAR(150) NOT NULL,
    nombre_archivo VARCHAR(200) NOT NULL,
    formato VARCHAR(20) NOT NULL DEFAULT 'java',
    contenido_codigo TEXT NOT NULL,
    fecha_creacion_codigo DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT fk_codigo_actividad FOREIGN KEY (id_actividad)
        REFERENCES actividad (id_actividad) ON DELETE RESTRICT,
    CONSTRAINT fk_codigo_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE RESTRICT
);

CREATE INDEX idx_seccion_usuario ON seccion (id_usuario);
CREATE INDEX idx_seccion_estudiante_usuario ON seccion_estudiante (id_usuario);
CREATE INDEX idx_seccion_actividad_actividad ON seccion_actividad (id_actividad);
CREATE INDEX idx_codigo_usuario ON codigo (id_usuario);
CREATE INDEX idx_codigo_actividad ON codigo (id_actividad);

COMMIT;
